#!/bin/sh

bspc config border_width        0
bspc config window_gap          0

bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true
#bspc config focus_by_distance    true
#bspc config history_aware_focus  true

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
# bspc monitor HDMI-1 -d  X

bspc config normal_border_color "#fc1da7"
bspc config focused_border_color "#fba506"
